[package]
name = "axum-rest-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.4"  # Use the latest version
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
